"""followers

Revision ID: 41535838234b
Revises: b5b5882bcb14
Create Date: 2020-02-03 12:49:53.151198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41535838234b'
down_revision = 'b5b5882bcb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
